version: '3.8'

services:
  backend:
    build: ./backend
    image: atlal-backend:latest
    container_name: atlal-backend
    restart: always
    env_file:
      - backend/.env
    ports:
      - "5050:5000"
    networks:
      - atlal-network

  frontend:
    build: ./frontend
    image: atlal-frontend:latest
    container_name: atlal-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - atlal-network

networks:
  atlal-network:
    driver: bridge