version: '3.8'

services:
  backend:
    build: ./backend
    restart: always
    environment:
      - MONGODB_URI=mongodb+srv://your_user:your_password@cluster.mongodb.net/atlal
      - PORT=5000
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend