name: Deploy Atlal Archive

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. Cleanup host port 80
            sudo systemctl stop nginx || true
            sudo fuser -k 80/tcp || true 

            # 2. Sync code
            cd ~/atlal-project
            git pull origin main

            # 3. Docker Rebuild (No more OOM errors!)
            sudo docker-compose up -d --build
            sudo docker-compose up -d --build
            sudo docker image prune -f